development:
  adapter: postgresql
  database: kushboo-dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kushboo-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kushboo
  pool: 5
  timeout: 5000