# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c8b50cc0833ac14e71b71a7951bf21da3febd4e5aaa532db90e0db61797c084ad5cd6d890cb014de17255543d6cffecce0f9faf63bd728a927894bb95897ad5

test:
  secret_key_base: 0d6c2d90a634a2cdd4fcc11564986e4876462f058d422ffa47555eae6c7da3afac359a59ada03feb2637cfdf3403b9425b79333f9b668980a663f1d3b1b4b69a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
